-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 13:34:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema run_raily_run
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `run_raily_run` ;

-- -----------------------------------------------------
-- Schema run_raily_run
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `run_raily_run` DEFAULT CHARACTER SET utf8 ;
USE `run_raily_run` ;

-- -----------------------------------------------------
-- Table `run_raily_run`.`Character`run_raily_run
-- -----------------------------------------------------run_raily_run
DROP TABLE IF EXISTS `run_raily_run`.`Character` ;

CREATE TABLE IF NOT EXISTS `run_raily_run`.`Character` (
  `idCharacter` INT NOT NULL AUTO_INCREMENT, 
  `name` VARCHAR(45) NOT NULL,
  `score_to_unlock` INT NOT NULL,
  PRIMARY KEY (`idCharacter`),
  UNIQUE INDEX `Charactercol_UNIQUE` (`score_to_unlock` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `run_raily_run`.`Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `run_raily_run`.`Player` ;

CREATE TABLE IF NOT EXISTS `run_raily_run`.`Player` (
  `idPlayer` INT NOT NULL AUTO_INCREMENT,
  `Character_idCharacter` INT NOT NULL,
  `best_score` INT NULL,
  PRIMARY KEY (`idPlayer`),
  UNIQUE INDEX `idPlayer_UNIQUE` (`idPlayer` ASC) VISIBLE,
  INDEX `fk_Player_Character_idx` (`Character_idCharacter` ASC) VISIBLE,
  CONSTRAINT `fk_Player_Character`
    FOREIGN KEY (`Character_idCharacter`)
    REFERENCES `run_raily_run`.`Character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `character` (name, score_to_unlock)
VALUES ('Raily', 0),
('Huey', 15000),
('Pelo_3', 40000);

INSERT INTO `player` (Character_idCharacter, best_score)
VALUES (1, 0);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
